import SideBar from "@/components/SideBar"
import "../globals.css"
import { AuthProvider } from "@/context/AuthContext"
import { ModalProvider } from "@/context/ModalContext"
import { Metadata } from "next"
import { Inter } from "next/font/google"
import React from "react"
import { ToastContainer } from "react-toastify"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
}

const Layout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <AuthProvider>
          <ModalProvider>
            <div className="bg-[#f2f2f2] flex w-full h-screen">
              <SideBar />
              {children}
            </div>
          </ModalProvider>
        </AuthProvider>
      </body>
    </html>
  )
}

export default Layout
